apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - image: $DOCKERHUB_USERNAME/$APP_NAME
        name: $APP_NAME
        env:
        - name: FIREBASE_PROJECT_ID
          value: "$FIREBASE_PROJECT_ID"
        - name: FIREBASE_PRIVATE_KEY_ID
          value: "$FIREBASE_PRIVATE_KEY_ID"
        - name: FIREBASE_PRIVATE_KEY
          value: "$FIREBASE_PRIVATE_KEY"
        - name: FIREBASE_CLIENT_EMAIL
          value: "$FIREBASE_CLIENT_EMAIL"
        - name: FIREBASE_CLIENT_ID
          value: "$FIREBASE_CLIENT_ID"
        - name: FIREBASE_CLIENT_X509_CERT_URL
          value: "$FIREBASE_CLIENT_X509_CERT_URL"

---

apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  type: ClusterIP
  ports:
  - name: $APP_NAME
    port: 8000
  selector:
    app: $APP_NAME

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $APP_NAME
  annotations:
    dev.okteto.com/generate-host: $APP_NAME
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: $APP_NAME
                port:
                  number: 8000
            path: /
            pathType: ImplementationSpecific
